"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

https://leetcode.com/problems/find-the-difference/

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e
"""


# @param string s original string
# @param string t string generated by random shuffling of s and adding one more letter at a random position
def find_the_difference(s, t):
    s_map = {}
    for character in s:
        if character in s_map:
            s_map[character] = s_map[character] + 1
        else:
            s_map[character] = 1

    for t_character in t:
        if t_character in s_map and s_map[t_character] != 0:
            s_map[t_character] = s_map[t_character] - 1
        else:
            return t_character

    return None


if __name__ == '__main__':
    assert find_the_difference("abcd", "abcde") == "e"
    assert find_the_difference("abcd", "afbcd") == "f"
    assert find_the_difference("", "") is None
    print("All test cases passed successfully")
